wavelength: 1550
max_components: 15

source:
  axis: 'xy'
  Nx: 166
  Ny: 166
  Nz: None
  Lx: 2040
  Ly: 2040
  Lz: None
  center: [0, 0, 0]

receiver:
  axis: 'xy'
  Nx: 166
  Ny: 166
  Nz: None
  Lx: 2040
  Ly: 2040
  Lz: None
  center: [0, 0, 775]

plot_plane:
  axis: 'xy'
  discretization: 166
  Lx: 2040
  Ly: 2040
  Lz: None
  z_idx: 0
  center: [0, 0, 775]
