apiVersion: v1
kind: Pod
metadata:
  name: monitor-braket
spec:
  containers:
    - name: monitor-braket
      image: docker.io/kovaleskilab/braket-optics:v1
      stdin: True
      tty: True
      resources:
        limits:
          memory: 4G
          cpu: 2
        requests:
          memory: 4G
          cpu: 2
      volumeMounts:
        - name: braket-results
          mountPath: /develop/results
        - name: braket-code
          mountPath: /develop/code
        - name: meep-dataset-v2 
          mountPath: /develop/data
        - name: dshm
          mountPath: /dev/shm
  volumes:
    - name: meep-dataset-v2
      persistentVolumeClaim:
        claimName: meep-dataset-v2
    - name: braket-results
      persistentVolumeClaim:
        claimName: braket-results
    - name: braket-code
      persistentVolumeClaim:
        claimName: braket-code
    - name: dshm
      emptyDir:
        medium: Memory

  restartPolicy: Never
